Beginnings of dmem (giving error)
dmem.v:18: syntax error
dmem_tb.v:2: invalid module item
dmem_tb.v:7: readData write conflicts with reg definition at dmem.v:7
dmem_tb.v:7: error: ''readData'' has already been declared